### ISSUE TITLE
arccw issue

### ISSUE THREAD

**Issue by GittyMuh** [Vaingald/GmodDynamicWeaponReverb#1]
basic issue: no arccw weapon work with this mod
advanced issue: when im close to a wall and i shoot the wall. the reverb sounds work. when im far and i shoot a wall it doesnt work. when i shoot indoors or shoot in the sky it doesnt work. when i get close to a wall and shoot the wall indoors it works.

**Comment by GittyMuh** [comment]
suppressor support doesnt seem to work..?

**Comment by relaxtakenotes** [comment]
check the newest update in workshop.
about suppressor support not working it may be subjective since i tried to keep it realistic (suppressors are not that good at suppressing shots, they're still loud as shit)
anyway, once you try out the new update and it still doesnt work please tell me what weapon pack you use so that i can investigate the issue in detail

**Comment by GittyMuh** [comment]
> check the newest update in workshop. about suppressor support not working it may be subjective since i tried to keep it realistic (suppressors are not that good at suppressing shots, they're still loud as shit) anyway, once you try out the new update and it still doesnt work please tell me what weapon pack you use so that i can investigate the issue in detail

im testing it right now. also arccw is arccw. the pack doesnt matter if its the base causing the issues.
thx for replying

**Comment by GittyMuh** [comment]
> check the newest update in workshop. about suppressor support not working it may be subjective since i tried to keep it realistic (suppressors are not that good at suppressing shots, they're still loud as shit) anyway, once you try out the new update and it still doesnt work please tell me what weapon pack you use so that i can investigate the issue in detail

im having the same issues as i stated in the start

**Comment by GittyMuh** [comment]
> basic issue: no arccw weapon work with this mod advanced issue: when im close to a wall and i shoot the wall. the reverb sounds work. when im far and i shoot a wall it doesnt work. when i shoot indoors or shoot in the sky it doesnt work. when i get close to a wall and shoot the wall indoors it works.

same issues. all weapon packs.

**Comment by relaxtakenotes** [comment]
> > check the newest update in workshop. about suppressor support not working it may be subjective since i tried to keep it realistic (suppressors are not that good at suppressing shots, they're still loud as shit) anyway, once you try out the new update and it still doesnt work please tell me what weapon pack you use so that i can investigate the issue in detail
> 
> im testing it right now. also arccw is arccw. the pack doesnt matter if its the base causing the issues. thx for replying

Well the thing is that different weapon packs may have different bullet source offsets which I use in penetration checks, that's why I'm wondering. 
I tested the mod right now and I hear reverb on all modern warfare 2019, tfa and arccw weapons. That's also why I'm asking you to prove the weapon pack link otherwise I will be unable to help you in any way.

**Comment by relaxtakenotes** [comment]
> > basic issue: no arccw weapon work with this mod advanced issue: when im close to a wall and i shoot the wall. the reverb sounds work. when im far and i shoot a wall it doesnt work. when i shoot indoors or shoot in the sky it doesnt work. when i get close to a wall and shoot the wall indoors it works.
> 
> same issues. all weapon packs.

Oh, I also forgot to mention one thing.
I've noticed that the shooting hook doesn't successfully run sometimes, I've recently pushed a fix for that and the mod creaotr just now pushed the update to workshop. Check it out again.

**Comment by relaxtakenotes** [comment]
I am not even going to be humble about this but FUCKING HELL WHY IS ARCCW CHANGING SO MUCH!!!!!!!!!!!
Anyway, I gotta update the correction code to fit the newer version of arccw so yeah, it wont take long.

**Comment by relaxtakenotes** [comment]
Fixed, author pushed the update to the workshop page.
