### ISSUE TITLE
huge issue

### ISSUE THREAD

**Issue by GittyMuh** [Vaingald/GmodDynamicWeaponReverb#10]
tfa weapons indoor sounds are ignored by the "only one reverb trail at a time" making the weapons sound like earape if the shotgun shoots more then 3 pellets at a shot.
make it so guns make sounds PER SHOT and not PER AMOUNT OF HITSCANS PER SHOT

**Comment by relaxtakenotes** [comment]
Problem: the entity fire hook is called more than 3 times on shotguns and there's nothing I can do to fix it. However I bet there's a fix available for the weapon creators themselves but their poor life choices have led them to not use them.

**Comment by GittyMuh** [comment]
can you make an ignore function
use 1. ignore the other 2

**Comment by GittyMuh** [comment]
so only one of the fire hooks count for your addon

**Comment by GittyMuh** [comment]
also can you finally check the issue i opened on your step delay changer addon

**Comment by relaxtakenotes** [comment]
i barely check that cause the mod isn't that commonly used lol but sure i'll check it out soon

**Comment by relaxtakenotes** [comment]
> so only one of the fire hooks count for your addon

Not possible.

**Comment by GittyMuh** [comment]
> > so only one of the fire hooks count for your addon
> 
> Not possible.

sad

**Comment by GittyMuh** [comment]
> i barely check that cause the mod isn't that commonly used lol but sure i'll check it out soon

thanks!

**Comment by GittyMuh** [comment]
> > so only one of the fire hooks count for your addon
> 
> Not possible.

but how come the "use one" on the reverb works for open areas but not indoors

**Comment by GittyMuh** [comment]
you could try supporting both indoors and outdoors and it would be the easyest fix

**Comment by relaxtakenotes** [comment]
> > > so only one of the fire hooks count for your addon
> > 
> > 
> > Not possible.
> 
> but how come the "one reverb trail" on the reverb works for open areas but not indoors

Well that's just a bug and it's possible to fix. But fixing shotgun bullets specifically isn't possible, at least from what data I'm presented with in the hook.

**Comment by GittyMuh** [comment]
> > > > so only one of the fire hooks count for your addon
> > > 
> > > 
> > > Not possible.
> > 
> > 
> > but how come the "one reverb trail" on the reverb works for open areas but not indoors
> 
> Well that's just a bug and it's possible to fix. But fixing shotgun bullets specifically isn't possible, at least from what data I'm presented with in the hook.

well if anything. can you fix the indoors reverb trails. thats all im asking. i hate the earrape of shotguns indoors. thanks!

**Comment by relaxtakenotes** [comment]
> > > > > so only one of the fire hooks count for your addon
> > > > 
> > > > 
> > > > Not possible.
> > > 
> > > 
> > > but how come the "one reverb trail" on the reverb works for open areas but not indoors
> > 
> > 
> > Well that's just a bug and it's possible to fix. But fixing shotgun bullets specifically isn't possible, at least from what data I'm presented with in the hook.
> 
> well if anything. can you fix the indoors reverb trails. thats all im asking. i hate the earrape of shotguns indoors. thanks!

Later. Currently I have no time

**Comment by GittyMuh** [comment]
> > > > > > so only one of the fire hooks count for your addon
> > > > > 
> > > > > 
> > > > > Not possible.
> > > > 
> > > > 
> > > > but how come the "one reverb trail" on the reverb works for open areas but not indoors
> > > 
> > > 
> > > Well that's just a bug and it's possible to fix. But fixing shotgun bullets specifically isn't possible, at least from what data I'm presented with in the hook.
> > 
> > 
> > well if anything. can you fix the indoors reverb trails. thats all im asking. i hate the earrape of shotguns indoors. thanks!
> 
> Later. Currently I have no time

understood

**Comment by GittyMuh** [comment]
arent you able to set a limit to how many fire hooks are called or what ever. by any chance.

**Comment by GittyMuh** [comment]
can youcheck your speed changer addons issues list. i put up a new issue.

**Comment by relaxtakenotes** [comment]
Fixed (finally!!!)
