### ISSUE TITLE
Reverb on MW Melee

### ISSUE THREAD

**Issue by BlackburnB2** [Vaingald/GmodDynamicWeaponReverb#2]
Reverbs come out of my weapon whenever I use Modern Warfare's weapon bash.

It is because that the bash uses some sort of bullets - which is why there are bullet hole decals whenever I bash a wall?

**Comment by relaxtakenotes** [comment]
you are correct, it is because they just use bullets with a really short distance.
i tried to accomodate for it but for some reason it emerged again, i'll see what i can do about it

**Comment by relaxtakenotes** [comment]
yes, my memory isn't failing me, i just accidentally deleted the distance check, oops! gonna return it real quick.
