### ISSUE TITLE
CW2.0 Support

### ISSUE THREAD

**Issue by shelbynotcar** [Vaingald/GmodDynamicWeaponReverb#3]
I suggest you add support for suppressed CW2.0 weapons as well. Believe it or not, a lot of people still use it.
Thanks in advance

**Comment by shelbynotcar** [comment]
A good start would be to get active attachment and then check it with `att.isSuppressor = true`

**Comment by relaxtakenotes** [comment]
That's so ancient... No cHands either... But I heard you, might do it a bit later.

**Comment by relaxtakenotes** [comment]
Added to the repo. Will take some time until the author will upload it on the workshop.
