### ISSUE TITLE
Addon causing errors when using ArcCW weapons

### ISSUE THREAD

**Issue by Unity456** [Vaingald/GmodDynamicWeaponReverb#5]
[Dynamic Weapon Reverb] lua/autorun/shared.lua:119: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. fn - lua/autorun/shared.lua:119
    3. unknown - lua/ulib/shared/hook.lua:109
     4. OldFireBullets - [C]:-1
      5. FireBullets - lua/autorun/lfs_basescript.lua:41
       6. DoPrimaryFire - lua/weapons/arccw_base/sh_firing.lua:583
        7. unknown - lua/weapons/arccw_base/sh_firing.lua:398

This is the error prompt that I get from firing any ArcCW weapon on any map under any conditions. It works fine with TFA and other kinds of weapons.
I have not modified any ArcCW or Reverb mod's settings and it was all fine just yesterday.

**Comment by relaxtakenotes** [comment]
https://github.com/Vaingald/GmodDynamicWeaponReverb/issues/4

Already fixed and should've been pushed to the workshop but it appears the update wasn't ever published there. Until then you may use the github version.

**Comment by relaxtakenotes** [comment]
It's properly updated now.
