### ISSUE TITLE
im confused

### ISSUE THREAD

**Issue by GittyMuh** [Vaingald/GmodDynamicWeaponReverb#7]
you say your addon works with  any arccw weapon you use. but when i test it with the most popular arccw weapons none work
arccw bo1pack
arccw urban coalition/decay/what ever the fuck
and... practically any addon i have. doesnt work with the addon
https://cdn.discordapp.com/attachments/881137328754671626/905432194137350144/it_doesnt_work_with_any_of_these.png

**Comment by GittyMuh** [comment]
the bo1 pack has a lot of different categorys. none of them work with your addon.

**Comment by GittyMuh** [comment]
i think i figured out the issue (DIDNT TEST YET)
does this work with physbullets for arccw

**Comment by GittyMuh** [comment]
ISSUE RESOLVED
THE PROBLEM WAS PHYSICAL BULLETS THIS ENTIRE TIME
I HATE HITSCAN CAUSE RANGED COMBAT IS POO WITHOUT BULLET TRAVEL TIME
MY ISSUE WAS THAT I WAS USING PHYS BULLETS

**Comment by relaxtakenotes** [comment]
Physical bullets implementation in any mod is pure jank because of gmod lua limitations, therefore we're not able to support it.
