### ISSUE TITLE
TFA Conflict

### ISSUE THREAD

**Issue by BillyJoeBob88** [Vaingald/GmodDynamicWeaponReverb#8]
When shooting unsilenced this error occurs. Seems to only happen with this weapon though, 
https://steamcommunity.com/sharedfiles/filedetails/?id=1676032134

[ERROR] lua/autorun/shared.lua:119: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. __event - lua/autorun/shared.lua:119
    3. OldFireBullets - [C]:-1
     4. FireBullets - lua/autorun/lfs_basescript.lua:41
      5. BallisticFirebullet - lua/weapons/tfa_gun_base/common/bullet.lua:54
       6. ShootBullet - lua/weapons/tfa_gun_base/common/bullet.lua:333
        7. ShootBulletInformation - lua/weapons/tfa_gun_base/common/bullet.lua:94
         8. TriggerAttack - lua/weapons/tfa_gun_base/shared.lua:1635
          9. unknown - lua/weapons/tfa_gun_base/shared.lua:1680 (x4)

**Comment by relaxtakenotes** [comment]
For some very interesting reason, the weapon name contains "cw_" which triggers the customizable weaponry statement instead of tfa. I'm going to find a more reliable way of defining what weapon pack people use, because so far the one I'm using caused too much issues.

**Comment by relaxtakenotes** [comment]
Fixed in the github repo. Soon to be pushed on the workshop...
