### ISSUE TITLE
NUT's report

### ISSUE THREAD

**Issue by PresidentNUT** [Vaingald/GmodDynamicWeaponReverb#9]
So first of all, it works great with most things, the problem is that not all weapons are audably compatable, I.E. TFA Starwars. The issue comes from how the audio mixes into the weapons which doesn't sound great with Sci-fi weapons, which easily breaks immersion, anything that can be done to ensure that there is better compatability for Sci-fi weapons would be great, I would like to use this for my server, but I can't until we could get Sci-fi weapon compatability, more specifically Starwars compatability. Thats all.

**Comment by relaxtakenotes** [comment]
We came to a conclusion that it would be the best for you to not use this mod for your server. There are no special sounds planned to be made for such weapons.
